package com.example.kinetixfsl.data.local

import androidx.room.Dao
import androidx.room.Entity
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.Transaction

// ─────────────────────────────────────────────────────────────────────────────
// Activity-log tables — the raw event data the Profile analytics are computed
// from. All scoped by `uid`.
// ─────────────────────────────────────────────────────────────────────────────

/** One row per calendar day of activity: signs learned, study seconds, active flag. */
@Entity(tableName = "activity_day", primaryKeys = ["uid", "epochDay"])
data class ActivityDayEntity(
    val uid: String,
    val epochDay: Long,
    val learnedCount: Int,
    val studySeconds: Long,
    val active: Boolean,
)

/** 24 rows per account (hour 0..23): practice sessions, quiz-correct and quiz-attempts. */
@Entity(tableName = "activity_hour", primaryKeys = ["uid", "hour"])
data class ActivityHourEntity(
    val uid: String,
    val hour: Int,
    val histogram: Int,
    val correct: Int,
    val attempts: Int,
)

/** signId → the epoch day it was last practiced (for skill-decay analytics). */
@Entity(tableName = "sign_last_practiced", primaryKeys = ["uid", "signId"])
data class SignLastPracticedEntity(val uid: String, val signId: String, val epochDay: Long)

/** categoryId → lessons started/completed (for module drop-off). */
@Entity(tableName = "lesson_count", primaryKeys = ["uid", "categoryId"])
data class LessonCountEntity(val uid: String, val categoryId: String, val started: Int, val completed: Int)

/** categoryId → quiz answers correct/attempts (for adaptive-difficulty accuracy). */
@Entity(tableName = "category_quiz_stat", primaryKeys = ["uid", "categoryId"])
data class CategoryQuizStatEntity(val uid: String, val categoryId: String, val correct: Int, val attempts: Int)

/** Camera-practice failure reason ("handshape"/"motion"/"timing") → count. */
@Entity(tableName = "camera_error", primaryKeys = ["uid", "errorType"])
data class CameraErrorEntity(val uid: String, val errorType: String, val count: Int)

/** One row per recent wrong quiz answer (ordered by autogenerated id, oldest first). */
@Entity(tableName = "quiz_mistake")
data class QuizMistakeEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val uid: String,
    val targetSignId: String,
    val targetWord: String,
    val chosenWord: String,
    val epochDay: Long,
)

@Dao
interface ActivityDao {

    @Query(
        "SELECT (SELECT COUNT(*) FROM activity_day WHERE uid = :uid) + " +
            "(SELECT COUNT(*) FROM activity_hour WHERE uid = :uid) + " +
            "(SELECT COUNT(*) FROM quiz_mistake WHERE uid = :uid)",
    )
    fun rowCount(uid: String): Int

    @Query("SELECT * FROM activity_day WHERE uid = :uid")
    fun days(uid: String): List<ActivityDayEntity>

    @Query("SELECT * FROM activity_hour WHERE uid = :uid")
    fun hours(uid: String): List<ActivityHourEntity>

    @Query("SELECT * FROM sign_last_practiced WHERE uid = :uid")
    fun signLastPracticed(uid: String): List<SignLastPracticedEntity>

    @Query("SELECT * FROM lesson_count WHERE uid = :uid")
    fun lessonCounts(uid: String): List<LessonCountEntity>

    @Query("SELECT * FROM category_quiz_stat WHERE uid = :uid")
    fun categoryStats(uid: String): List<CategoryQuizStatEntity>

    @Query("SELECT * FROM camera_error WHERE uid = :uid")
    fun cameraErrors(uid: String): List<CameraErrorEntity>

    @Query("SELECT * FROM quiz_mistake WHERE uid = :uid ORDER BY id ASC")
    fun mistakes(uid: String): List<QuizMistakeEntity>

    @Insert(onConflict = OnConflictStrategy.REPLACE) fun insertDays(rows: List<ActivityDayEntity>)
    @Insert(onConflict = OnConflictStrategy.REPLACE) fun insertHours(rows: List<ActivityHourEntity>)
    @Insert(onConflict = OnConflictStrategy.REPLACE) fun insertSignLastPracticed(rows: List<SignLastPracticedEntity>)
    @Insert(onConflict = OnConflictStrategy.REPLACE) fun insertLessonCounts(rows: List<LessonCountEntity>)
    @Insert(onConflict = OnConflictStrategy.REPLACE) fun insertCategoryStats(rows: List<CategoryQuizStatEntity>)
    @Insert(onConflict = OnConflictStrategy.REPLACE) fun insertCameraErrors(rows: List<CameraErrorEntity>)
    @Insert(onConflict = OnConflictStrategy.REPLACE) fun insertMistakes(rows: List<QuizMistakeEntity>)

    @Query("DELETE FROM activity_day WHERE uid = :uid") fun deleteDays(uid: String)
    @Query("DELETE FROM activity_hour WHERE uid = :uid") fun deleteHours(uid: String)
    @Query("DELETE FROM sign_last_practiced WHERE uid = :uid") fun deleteSignLastPracticed(uid: String)
    @Query("DELETE FROM lesson_count WHERE uid = :uid") fun deleteLessonCounts(uid: String)
    @Query("DELETE FROM category_quiz_stat WHERE uid = :uid") fun deleteCategoryStats(uid: String)
    @Query("DELETE FROM camera_error WHERE uid = :uid") fun deleteCameraErrors(uid: String)
    @Query("DELETE FROM quiz_mistake WHERE uid = :uid") fun deleteMistakes(uid: String)

    @Transaction
    fun replaceAll(
        uid: String,
        days: List<ActivityDayEntity>,
        hours: List<ActivityHourEntity>,
        signLastPracticed: List<SignLastPracticedEntity>,
        lessonCounts: List<LessonCountEntity>,
        categoryStats: List<CategoryQuizStatEntity>,
        cameraErrors: List<CameraErrorEntity>,
        mistakes: List<QuizMistakeEntity>,
    ) {
        wipe(uid)
        insertDays(days)
        insertHours(hours)
        insertSignLastPracticed(signLastPracticed)
        insertLessonCounts(lessonCounts)
        insertCategoryStats(categoryStats)
        insertCameraErrors(cameraErrors)
        insertMistakes(mistakes)
    }

    @Transaction
    fun wipe(uid: String) {
        deleteDays(uid)
        deleteHours(uid)
        deleteSignLastPracticed(uid)
        deleteLessonCounts(uid)
        deleteCategoryStats(uid)
        deleteCameraErrors(uid)
        deleteMistakes(uid)
    }
}
